services:
  - type: web
    name: pdf-remediation-api
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: pdf-remediation-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_HTTP_PORTS
        value: "8080"

databases:
  - name: pdf-remediation-db
    plan: free
    region: ohio
