services:
  - type: web
    name: pdf-remediation-api
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: pdf-remediation-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_hostBuilder__reloadConfigOnChange
        value: "false"
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

databases:
  - name: pdf-remediation-db
    plan: free
    region: ohio
